### ISSUE TITLE
UndefinedCredentials

### ISSUE THREAD

**Issue by annaelleSSS** [Dwolla/dwolla-v2-node#27]
My goal is to create customers directly from my knack app (knack.com). 
I only have a dedicated area to put some javascript otherwise it's only drag and drop. I'm not an expert at all and I don't understand why I keep having a 401 error. 
Thank you so much for your help. 

   var urlDwolla= 'https://api-sandbox.dwolla.com/customers'; 
  // var authorization = {client_id:"XXX", client_secret:"YYYY"};
   var authorization ='Token Access';
    
   $.ajax({
    //beforeSend: function(request) {
  	//  request.setRequestHeader('Authorization', 'Bearer ' + authorization);
        //  request.setRequestHeader('Accept', 'application/json');
        //  request.setRequestHeader('content-type','application/json');
  	},
    url: urlDwolla,
    type: 'POST',
    headers: {
		'Accept': 'application/json',
		'Authorization': 'Bearer ' + authorization,
     	'content-type':'application/json',
    }, 
    success: function (response) {
  		console.log('success');
    }
  });

**Comment by spencerhunter** [comment]
Hi @annaelleSSS , Unfortunately Dwolla does not offer a client-side Javascript library for creating Customer accounts. Requests to the Dwolla API should be made by your backend server(s), which should securely store your API credentials and manage other business logic surrounding payments. This helper library may not be the best option for what you're looking to accomplish.
