### ISSUE TITLE
Invalid scope when creating customers

### ISSUE THREAD

**Issue by jocull** [Dwolla/dwolla-v2-node#3]
I'm having trouble creating a new white-label customer. I'm getting an error about invalid scopes, which I do not understand...

Here is the code that makes the request (using variables from my config)

```js
const config = require('config');
const dwolla = require('dwolla-v2');

const Client = new dwolla.Client({
    id: config.dwolla.client_id,
    secret: config.dwolla.client_secret,
    environment: 'sandbox',
});

Client.auth.client()
	.then(client => {
		return client.post('customers', {
		    firstName: 'James',
		    lastName: 'Smith',
		    email: 'james@smith.com',
		    type: 'receive-only',
		})
	})
```
I can tell that the token is being registered, and it appears to have all the appropriate scopes:

```js
{ client: 
   Client {
     id: '................',
     secret: '...............',
     environment: 'sandbox',
     onGrant: [Function],
     authUrl: 'https://uat.dwolla.com/oauth/v2/authenticate',
     tokenUrl: 'https://uat.dwolla.com/oauth/v2/token',
     apiUrl: 'https://api-uat.dwolla.com',
     auth: 
      { client: [Function: bound requestToken],
        refresh: [Function: bound refreshGrant] },
     Auth: [Function: bound AuthClass],
     Token: [Function: bound ] },
  access_token: '..........',
  refresh_token: undefined,
  expires_in: 1514,
  scope: 'accountinfofull|contacts|transactions|balance|send|request|funding|manageaccount|scheduled|email|managecustomers',
  account_id: undefined }
```
But then this error is thrown by the promise:

```
Error: the object {
  "body": {
    "code": "InvalidScope"
    "message": "Missing or invalid scopes for requested endpoint."
  }
  "headers": {
    "_headers": {
      "access-control-allow-origin": [
        "*"
      ]
      "cf-ray": [
        "2af63796438710cf-ORD"
      ]
      "connection": [
        "close"
      ]
      "content-length": [
        "85"
      ]
      "content-type": [
        "application/vnd.dwolla.v1.hal+json; profile=\"http://nocarrier.co.uk/profiles/vnd.error/\"; charset=UTF-8"
      ]
      "date": [
        "Tue, 07 Jun 2016 18:37:46 GMT"
      ]
      "server": [
        "cloudflare-nginx"
      ]
      "set-cookie": [
        "__cfduid=da84a0940368fa7ce4622b1d73888cb2e1465324665; expires=Wed, 07-Jun-17 18:37:45 GMT; path=/; domain=.dwolla.com; HttpOnly"
      ]
    }
  }
  "status": 401
} was thrown, throw an Error :)
```

Why is this? I have the `managecustomers` scope as far as I can tell.

**Comment by alex4Zero** [comment]
Make sure you set `access_token` before doing the request
Here is an example I have which works fine
  ```
var client = new dwolla.Client({
    id: config.dwolla.id,
    secret: config.dwolla.secret,
    environment: config.dwolla.environment
  });

var accountToken = new client.Token({access_token: config.dwolla.token});

var createCustomer = function() {
    var requestBody = {
        firstName: "Alex",
        lastName: "Andronov",
        email: "email@email.com"
    };

    accountToken
        .post("customers", requestBody)
        .then(function(acc) {
                console.log(acc);
            },
            function(err) {
                console.log(err);
            });
};

```

**Comment by sausman** [comment]
Hey @jocull,

The token created using `Client.auth.client()` is an application token which can only be used for `/events`, `/webhook-subscriptions` and a couple other endpoints. You'll need to create an account token in order to create customers, add funding sources, send money, etc. You can get an account token by setting up the OAuth flow in your app or generating a token pair at dwolla.com/applications.

Sorry for the confusion, let me know if you have any questions!

**Comment by jocull** [comment]
@sausman In production, are you able to create an account token that last indefinitely? We're not out of the sandbox yet, so I just wanted to make sure I wasn't digging a hole for later.

**Comment by sausman** [comment]
@jocull For security reasons we expire all access tokens after 1 hour in production. When you go to production you'll need to implement token refreshing. There are a couple different techniques so let us know if you have any questions, we're happy to go over them with you.

**Comment by jocull** [comment]
Thanks @sausman. Since this is more related to the Dwolla API and not this package I will close this and carry on here: https://discuss.dwolla.com/t/missing-or-invalid-scopes-for-creating-customer/2534
