### ISSUE TITLE
CORS issue with js sdk

### ISSUE THREAD

**Issue by EmanHerawy** [Dwolla/dwolla-v2-node#43]
Hey there, 
I was trying to use the sandbox js sdk  but I got CORS issue , how can I edit the request header using the sdk ?
I used this code 
```
// Using DwollaV2 - https://github.com/Dwolla/dwolla-v2-node
// This example assumes you've already initialized the client. Reference the SDKs page for more information: https://developers.dwolla.com/pages/sdks.html
client.auth.client()
  .then(function(appToken) {
    return appToken.get('/');
  })
  .then(function(res) {
    console.log(JSON.stringify(res.body));
  });
```
but I got 

> Failed to load https://api-sandbox.dwolla.com/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Thanks for your help in advance

**Comment by NickCarducci** [comment]
I know this is not best practice but _https://cors-anywhere.herokuapp.com/_
````
const appKey = "";
const appSecret = "";
await fetch(
 `https://cors-anywhere.herokuapp.com/https://api-sandbox.dwolla.com/token`,
  {
   method: "POST",
   headers: {
    "content-type": "application/x-www-form-urlencoded",
      Allow: "*",
      Accept: "application/json"
   },
   body: `grant_type=client_credentials&client_id=${appKey}&client_secret=${appSecret}`
  }
 )
.then(async response => await response.json())
.then(body => {
     console.log(body);
})
```

**Comment by EmanHerawy** [comment]
Thanks @NickCarducci for your help

**Comment by sausman** [comment]
Yeah, this particular client is only intended for use on a secure server running Node.js and not in a browser environment.

If you would like to make requests from the browser, we have [Dwolla.js](https://developers.dwolla.com/guides/dwolla-js/add-a-bank-account#add-a-bank-using-dwollajs) which supports a growing subset of API endpoints. Let us know if you have any questions!

**Comment by ianwolf99** [comment]
am really frustarted with dwolla api am building a payroll system but in sandbox am getting 500 , like wait 500 in sanbox, how do people use dwolla this is a big red flag see this   $ curl --ssl-no-revoke --request POST \
  --url https://api-sandbox.dwolla.com/token \
  --header 'Authorization: Basic [redacted]' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials'
error code: 500
   and error  {
    "error": "invalid json response body at https://api-sandbox.dwolla.com/token reason: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"
}  , this is terrible

**Comment by spencerhunter** [comment]
Hi @ianwolf99  , Apologies for the disruption, we were temporarily impacted by the [Cloudflare outage](https://apnews.com/article/cloudflare-outage-x-openai-9335e8e0da2a0027d1fbac5eb97d11ae) this morning which resulted in non-json responses being returned on API requests. This should be resolved now and the API operating as normal.
