### ISSUE TITLE
Use "files" in package.json, don't publish the world

### ISSUE THREAD

**Issue by shellscape** [Dwolla/dwolla-v2-node#48]
Hey folks, while hunting for accompanying TypeScript types in this package I noticed that you're publishing the entire contents of the repo to NPM. 

I'd like to humbly request that the package be updated to use the `files` property in package.json https://docs.npmjs.com/files/package.json#files.

It's also rather unorthodox these days to put non-compiled files into `src` in the NPM world. I'd suggest moving those to `lib` and publishing lib. Food for thought.

**Comment by rhuffy** [comment]
@shellscape Did you end up finding TypeScript types? I've created a PR for the declaration file I've been using here: #49
