### ISSUE TITLE
Calling the root

### ISSUE THREAD

**Issue by ajbraus** [Dwolla/dwolla-v2-node#59]
Hi there, I'm stuck just trying to get my account info and funding source id(s). Your documentation is great, except it doesn't include this extremely simple step. Any chance you could add this? Or better yet, if you tell me how to do it here, I'll submit a pull request to update your docs. Thanks!

**Comment by spencerhunter** [comment]
Hi @ajbraus , Thanks for opening up this issue! We're working on surfacing this information better within our documentation. In the meantime, here is a small script for calling the root and retrieving the List of Funding Sources for your Master Account. (Assuming you're referring to Funding Sources tied to your primary Dwolla Account and not a Customer record)

`npm i dwolla-v2`

put this in a file called test.js

```
const Client = require("dwolla-v2").Client;

const key = process.env.KEY;
const secret = process.env.SECRET;

const dwolla = new Client({
  key: key,
  secret: secret,
  environment: "sandbox", // defaults to 'production'
});

if (!key || !secret) throw new Error("KEY and SECRET env vars required");

dwolla
 .get("/")
    .then(res => {
      console.log(res.body._links.account.href);
      const accountUrl = res.body._links.account.href;
      return dwolla.get(`${accountUrl}/funding-sources?removed=false`);
    })
    .then(res => console.log(res.body._embedded['funding-sources']))
    .catch(error => console.error(error.body));
```
Run:
`KEY=YOUR_CLIENT_KEY SECRET=YOUR_CLIENT_SECRET node test.js`
