### ISSUE TITLE
Warning: a promise was rejected with a non-error:

### ISSUE THREAD

**Issue by faceyspacey** [Dwolla/dwolla-v2-node#8]
The errors passed to `reject(error)` that you receive in `.catch((error) => ...)` are not real error objects as per described here:

https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-rejected-with-a-non-error

I'm using the `client.auth.refresh` method. The error object I'm receiving is:

`
 { error: 'access_denied',
I20160826-22:28:27.722(-7)?   error_description: 'Invalid application credentials.' }
`

So it seems that should have a `stack` method and all the other standard error properties.methods, and generally be a real thrown error. 

It seems as though the node API is treating the error object as if it's the sort returned from a callback, eg: `(error, result) => ...`. Which usually aren't thrown style errors. 

It's just a warning--is the recommendation to developers just to ignore it? Is there a prescribed way to silence it? Or perhaps is this a bug where we should make it a real error object, i.e: `instanceof Error`? I know a stack trace is basically not very useful here as the whole purpose of an API/sdk is for that not be the developer's problem (unless it's a real bug), and the sdk is just trying to convey errors of a different variety, i.e. incorrect usage of the API. 

I guess it wouldn't hurt to have the `stack`, `message`, and `name` keys, in addition to the keys you're already using, that way existing code that uses the SDK won't break, and developers won't receive this warning.

**Comment by sausman** [comment]
Hey @faceyspacey,

I wasn't aware of this warning. I will work on fixing it sometime this week, but I think your suggestions make sense. Thanks for the detailed issue!

**Comment by sausman** [comment]
@faceyspacey This should be fixed in v1.2.0. Thanks again for reporting the issue!
