### ISSUE TITLE
indexOf() === 0 vs startsWith()

### ISSUE THREAD

**Issue by MarcMouallem** [Dwolla/dwolla-v2-node#80]
`suppliedPath.indexOf(token.client.apiUrl) === 0` on line 34 and `suppliedPath.indexOf("/") === 0` on line 36 of Token.js should be replaced with `startsWith()`.

**Comment by jcoon97** [comment]
Thank you for the report! I have created a PR (#82) for this to be addressed in the next patch version.

**Comment by jcoon97** [comment]
PR has been approved. Will be available in the next update.
