### ISSUE TITLE
Facing CORS issue in token API

### ISSUE THREAD

**Issue by ajithK24** [Dwolla/dwolla-v2-node#91]
Hey there,
I was trying to use the sandbox js sdk but I got CORS issue , how can I edit the request header using the sdk ?
I used this code

// Using DwollaV2 - https://github.com/Dwolla/dwolla-v2-node
// This example assumes you've already initialized the client. Reference the SDKs page for more information: 

 var Client = require("dwolla-v2").Client;

    const appKey = "";
const appSecret = "";
var dwolla = new Client({
  key: appKey,
  secret: appSecret,
  environment: "sandbox", 
});

dwolla
  .post("token")
  .then((res:any) => {
    console.log(res.body.total)
  } );
but I got

Failed to load https://api-sandbox.dwolla.com/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200/' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Thanks for your help in advance
<img width="1049" alt="Screenshot 2022-12-08 at 2 21 40 PM" src="https://user-images.githubusercontent.com/66124090/206401634-2d929541-ce51-421e-83d9-9cc23ab3b0a3.png">

**Comment by tarricsookdeo** [comment]
Hi @ajithK24!

It seems like you are trying to access the `token` endpoint to create a new access token. The correct syntax for that is:

```javascript
const Client = require('dwolla-v2').Client;

// instantiate client
const dwolla = new Client({
  environment: 'sandbox',
  key: <KEY>,
  secret: <SECRET>
});

// Request to token endpoint
dwolla.auth
  .client()
  .then(res => console.log(res))

/*A token object should be console logged
Token {
  client: Client {
    key: <KEY>,
    id: <ID>,
    secret: <SECRET>,
    environment: 'sandbox',
    onGrant: undefined,
    authUrl: 'https://accounts-sandbox.dwolla.com/auth',
    tokenUrl: 'https://api-sandbox.dwolla.com/token',
    apiUrl: 'https://api-sandbox.dwolla.com',
    auth: [Function: methods] {
      client: [Function: bound requestToken],
      refresh: [Function: bound refreshGrant]
    },
    Auth: [Function: bound AuthClass],
    Token: [Function: bound Token],
    get: [Function (anonymous)],
    post: [Function (anonymous)],
    delete: [Function (anonymous)],
    refreshToken: [Function (anonymous)],
    token: [Function (anonymous)]
  },
  access_token: <ACCESS TOKEN>,
  refresh_token: undefined,
  expires_in: 3448,
  scope: undefined,
  account_id: undefined
}
*/
```

However, our Node SDK takes care of token management for you. You can simply make requests against the client using the low level methods `.get`, `.post`, and `.delete`. The SDK will check if you have a valid token, and if not request a new one automatically.

Also, our Node SDK is a server side-library and shouldn't be accessed via a web browser. Try making requests via Postman, CURL, or another type of server-side client. You can read up more about this issue here: https://discuss.dwolla.com/t/dwolla-post-giving-me-a-cors-error/7652/3?u=spencer.

**Comment by ajithK24** [comment]
> Hi @ajithK24!
> 
> It seems like you are trying to access the `token` endpoint to create a new access token. The correct syntax for that is:
> 
> ```js
> const Client = require('dwolla-v2').Client;
> 
> // instantiate client
> const dwolla = new Client({
>   environment: 'sandbox',
>   key: <KEY>,
>   secret: <SECRET>
> });
> 
> // Request to token endpoint
> dwolla.auth
>   .client()
>   .then(res => console.log(res))
> 
> /*A token object should be console logged
> Token {
>   client: Client {
>     key: <KEY>,
>     id: <ID>,
>     secret: <SECRET>,
>     environment: 'sandbox',
>     onGrant: undefined,
>     authUrl: 'https://accounts-sandbox.dwolla.com/auth',
>     tokenUrl: 'https://api-sandbox.dwolla.com/token',
>     apiUrl: 'https://api-sandbox.dwolla.com',
>     auth: [Function: methods] {
>       client: [Function: bound requestToken],
>       refresh: [Function: bound refreshGrant]
>     },
>     Auth: [Function: bound AuthClass],
>     Token: [Function: bound Token],
>     get: [Function (anonymous)],
>     post: [Function (anonymous)],
>     delete: [Function (anonymous)],
>     refreshToken: [Function (anonymous)],
>     token: [Function (anonymous)]
>   },
>   access_token: <ACCESS TOKEN>,
>   refresh_token: undefined,
>   expires_in: 3448,
>   scope: undefined,
>   account_id: undefined
> }
> */
> ```
> 
> However, our Node SDK takes care of token management for you. You can simply make requests against the client using the low level methods `.get`, `.post`, and `.delete`. The SDK will check if you have a valid token, and if not request a new one automatically.
> 
> Also, our Node SDK is a server side-library and shouldn't be accessed via a web browser. Try making requests via Postman, CURL, or another type of server-side client. You can read up more about this issue here: https://discuss.dwolla.com/t/dwolla-post-giving-me-a-cors-error/7652/3?u=spencer.

Ok @tarricsookdeo instead of node can we able to use JAVA ?

**Comment by tarricsookdeo** [comment]
@ajithK24 Yes, you are able to use Java to access Dwolla's API. We also have a Kotlin SDK that makes it easy to interact with the API using Java. Here is a link to it: https://github.com/Dwolla/dwolla-v2-kotlin
